"use client";

// KhataLedgerTableRow.tsx
// ─────────────────────────────────────────────────────────────────────────────
// Responsibility: Renders one transaction row in the Khata ledger table.
// Shows two layouts: Desktop (4-column grid) and Mobile (3-column grid).
// If the transaction has attached bill items, delegates rendering to
// KhataLedgerTransactionItemsList.
// Supports inline editing for manual transactions.
// ─────────────────────────────────────────────────────────────────────────────

import React, { useState } from "react";
import { format } from "date-fns";
import { ArrowUpRight, ArrowDownRight, Pencil, Check, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { KhataLedgerRow } from "@/app/(app)/khata/khata_types/KhataTypes";
import { KhataLedgerTransactionItemsList } from "@/app/(app)/khata/khata_components/Ledger/KhataLedgerTransactionItemsList";
import { useUpdateKhataTransaction, getGetCustomerQueryKey, getListCustomersQueryKey, getGetDashboardSummaryQueryKey } from "@/lib/api";
import { useKhata } from "@/app/(app)/khata/khata_context/KhataContext";
import { useQueryClient } from "@tanstack/react-query";
import { useToast } from "@/hooks/use-toast";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

interface KhataLedgerTableRowProps {
  tx: KhataLedgerRow;
}

export function KhataLedgerTableRow({ tx }: KhataLedgerTableRowProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [editAmount, setEditAmount] = useState(tx.amount.toString());
  const [editDesc, setEditDesc] = useState(tx.description);
  const [editType, setEditType] = useState<"credit" | "payment">(tx.type);

  const { selectedLedgerId } = useKhata();
  const updateTx = useUpdateKhataTransaction();
  const queryClient = useQueryClient();
  const { toast } = useToast();

  const handleSave = () => {
    if (!selectedLedgerId) return;
    const amount = parseFloat(editAmount);
    if (isNaN(amount) || amount <= 0) {
      toast({ title: "Invalid amount", variant: "destructive" });
      return;
    }
    
    updateTx.mutate(
      { id: selectedLedgerId, txId: tx.id, data: { amount, description: editDesc, type: editType } },
      {
        onSuccess: () => {
          toast({ title: "Transaction updated" });
          setIsEditing(false);
          queryClient.invalidateQueries({ queryKey: getGetCustomerQueryKey(selectedLedgerId) });
          queryClient.invalidateQueries({ queryKey: getListCustomersQueryKey() });
          queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() });
          queryClient.invalidateQueries({ queryKey: ["reports"] });
        },
        onError: () => toast({ title: "Failed to update", variant: "destructive" }),
      }
    );
  };

  const isAutoGenerated = tx.items && tx.items.length > 0;

  if (isEditing) {
    return (
      <div className="bg-[var(--khata-muted-hover-bg)] border-b border-[var(--khata-border)]">
        {/* ── Desktop Edit Form ──────────────────────────────────────────── */}
        <div className="hidden sm:grid grid-cols-[120px_1fr_130px_130px] items-center px-6 py-3 gap-3">
          <div className="text-sm text-[var(--khata-muted-text)]">
            {format(new Date(tx.createdAt), "dd MMM yyyy")}
          </div>
          <div className="flex items-center gap-2 pr-4">
            <select 
              className="h-8 rounded-md border bg-background px-2 text-xs"
              value={editType} 
              onChange={e => setEditType(e.target.value as "credit" | "payment")}
            >
              <option value="payment">Payment Mila (-)</option>
              <option value="credit">Udhaar Diya (+)</option>
            </select>
            <Input 
              className="h-8 flex-1 text-sm bg-[var(--khata-background)]" 
              value={editDesc} 
              onChange={e => setEditDesc(e.target.value)} 
              placeholder="Description"
            />
          </div>
          <div className="text-right">
            <Input 
              type="number" 
              className="h-8 w-24 ml-auto text-right text-sm font-semibold bg-[var(--khata-background)]" 
              value={editAmount} 
              onChange={e => setEditAmount(e.target.value)} 
            />
          </div>
          <div className="flex justify-end gap-1">
            <Button size="icon" variant="ghost" className="h-8 w-8 text-green-600 hover:text-green-700 hover:bg-green-50" onClick={handleSave} disabled={updateTx.isPending}>
              <Check size={16} />
            </Button>
            <Button size="icon" variant="ghost" className="h-8 w-8 text-red-600 hover:text-red-700 hover:bg-red-50" onClick={() => setIsEditing(false)}>
              <X size={16} />
            </Button>
          </div>
        </div>

        {/* ── Mobile Edit Form ───────────────────────────────────────────── */}
        <div className="sm:hidden flex flex-col gap-2 px-3 py-3">
          <div className="flex gap-2">
            <select 
              className="h-9 rounded-md border bg-background px-2 text-xs flex-1"
              value={editType} 
              onChange={e => setEditType(e.target.value as "credit" | "payment")}
            >
              <option value="payment">Payment Mila</option>
              <option value="credit">Udhaar Diya</option>
            </select>
            <Input 
              type="number" 
              className="h-9 w-24 text-right text-sm font-semibold bg-[var(--khata-background)]" 
              value={editAmount} 
              onChange={e => setEditAmount(e.target.value)} 
            />
          </div>
          <Input 
            className="h-9 text-sm bg-[var(--khata-background)]" 
            value={editDesc} 
            onChange={e => setEditDesc(e.target.value)} 
            placeholder="Description"
          />
          <div className="flex justify-end gap-2 mt-1">
            <Button size="sm" variant="outline" className="h-8 w-1/2" onClick={() => setIsEditing(false)}>Cancel</Button>
            <Button size="sm" className="h-8 w-1/2" onClick={handleSave} disabled={updateTx.isPending}>Save</Button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="group hover:bg-[var(--khata-muted-hover-bg)]">
      {/* ── Desktop Row ──────────────────────────────────────────── */}
      <div className="hidden sm:grid grid-cols-[120px_1fr_130px_130px] items-center px-6 py-4">
        <div className="text-sm text-[var(--khata-muted-text)]">
          {format(new Date(tx.createdAt), "dd MMM yyyy")}
        </div>
        <div className="flex items-start gap-3 pr-4">
          <div
            className={cn(
              "mt-0.5 h-6 w-6 rounded-full flex items-center justify-center shrink-0",
              tx.type === "credit"
                ? "bg-[var(--khata-tx-credit-icon-bg)] text-[var(--khata-tx-credit-icon-text)]"
                : "bg-[var(--khata-tx-payment-icon-bg)] text-[var(--khata-tx-payment-icon-text)]"
            )}
          >
            {tx.type === "credit" ? <ArrowUpRight size={15} /> : <ArrowDownRight size={15} />}
          </div>
          <p className="text-sm leading-tight text-[var(--khata-foreground)]">{tx.description}</p>
        </div>
        <div className="text-right font-semibold">
          <span
            className={
              tx.type === "credit"
                ? "text-[var(--khata-tx-credit-amount)]"
                : "text-[var(--khata-tx-payment-amount)]"
            }
          >
            {tx.type === "credit" ? "+" : "-"} ₹{tx.amount.toFixed(0)}
          </span>
        </div>
        <div className="text-right font-bold text-base text-[var(--khata-foreground)] flex items-center justify-end gap-2">
          <span>₹{tx.balance.toFixed(0)}</span>
          {!isAutoGenerated && (
            <button 
              onClick={() => setIsEditing(true)} 
              title="Edit Transaction"
              className="opacity-0 group-hover:opacity-100 transition-opacity text-[var(--khata-muted-text)] hover:text-primary"
            >
              <Pencil size={14} />
            </button>
          )}
        </div>
      </div>

      {/* ── Mobile Row ───────────────────────────────────────────── */}
      <div className="sm:hidden grid grid-cols-[80px_1fr_90px] items-center px-3 py-3">
        <div className="text-xs text-[var(--khata-muted-text)]">
          {format(new Date(tx.createdAt), "dd MMM")}
        </div>
        <div className="flex items-center gap-2 min-w-0">
          <div
            className={cn(
              "h-5 w-5 rounded-full flex items-center justify-center shrink-0",
              tx.type === "credit"
                ? "bg-[var(--khata-tx-credit-icon-bg)] text-[var(--khata-tx-credit-icon-text)]"
                : "bg-[var(--khata-tx-payment-icon-bg)] text-[var(--khata-tx-payment-icon-text)]"
            )}
          >
            {tx.type === "credit" ? <ArrowUpRight size={11} /> : <ArrowDownRight size={11} />}
          </div>
          <p className="text-xs truncate text-[var(--khata-foreground)]">{tx.description}</p>
        </div>
        <div className="text-right">
          <div
            className={cn(
              "text-xs font-semibold",
              tx.type === "credit"
                ? "text-[var(--khata-tx-credit-amount)]"
                : "text-[var(--khata-tx-payment-amount)]"
            )}
          >
            {tx.type === "credit" ? "+" : "-"}₹{tx.amount.toFixed(0)}
          </div>
          <div className="text-xs font-bold text-[var(--khata-foreground)] flex items-center justify-end gap-1.5">
            <span>₹{tx.balance.toFixed(0)}</span>
            {!isAutoGenerated && (
              <button 
                onClick={() => setIsEditing(true)} 
                className="opacity-0 group-hover:opacity-100 transition-opacity text-[var(--khata-muted-text)] hover:text-primary"
              >
                <Pencil size={12} />
              </button>
            )}
          </div>
        </div>
      </div>

      {/* ── Purchased Items Sub-List (delegated to its own component) ── */}
      {tx.items && tx.items.length > 0 && (
        <KhataLedgerTransactionItemsList items={tx.items} />
      )}
    </div>
  );
}
